<!DOCTYPE html>
<html lang="ru" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Users</title>
  </head>
  <body>
    <nav>
      <a href="/">main page</a>
    </nav>
    <hr>
    <h1>Users</h1>
    <form class="" action="/users" method="get">
      <input type="search" name="term" value="<?= $terms ?>">
      <input type="submit" name="" value="Search">
    </form>
    <br>

      <? foreach($messages as $mesage){
        foreach ($mesage as $key => $value) {
          if ($key = "success") {
            echo "<div style='background-color: green'>{$value}</div>";
          }
        }
      }?>

    <!-- <? var_dump($messages)?> -->
      <!-- <? var_dump($users) ?> -->
<table border="1">
  <tr><td>Name</td>
  <td>email</td>
  <td>city id</td></tr>

  <? foreach ($users as $user) {
    echo "
    <tr><td>{$user['name']}</td>
    <td>{$user['email']}</td>
    <td>{$user['city']}</td></tr>
    ";
  } ?>

</table>
  </body>
</html>
